// FECTH
export const TENANTS_FETCH_REQUESTED = 'TENANTS_FETCH_REQUESTED'
export const TENANT_JOBS_FETCH_REQUESTED = 'TENANT_JOBS_FETCH_REQUESTED'
// RECEIVE
export const TENANTS_RECEIVED = 'TENANTS_RECEIVED'
export const JOBS_RECEIVED = 'JOBS_RECEIVED'
// UI
export const TENANT_ACTIVATED = 'TENANT_ACTIVATED'
